// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accomodation_list: dynamic(() => import("./AccommodationList")),
  content: dynamic(() => import("./Content")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  hero_with_search: dynamic(() => import("./HeroWithSearch")),
  image_slider: dynamic(() => import("./ImageSlider")),
  tour_list: dynamic(() => import("./TourList")),
  transfer_contact_form_slice: dynamic(
    () => import("./TransferContactFormSlice"),
  ),
  transfer_service_slice: dynamic(() => import("./TransferServiceSlice")),
};
